### ISSUE TITLE
Error with strict dependency injection

### ISSUE THREAD

**Issue by vhpgomes** [lpsBetty/angular-croppie#1]
When using the directive ng-strict-di, the code breaks, complaining that the controller is not using "explicit annotation"

Changing the code to use the explicit annotation makes it more robust, as it will work with or without the ng-strict-di directive.

`controller: function ($scope, $element) { ...`

to

`controller: ['$scope', '$element', function ($scope, $element) {`

The code change is really small, and I have created a pull request with it, if you want to use it.

**Comment by bettysteger** [comment]
Hey, sorry for the late response, this is not really a issue for this module... It is just how you develop, my preference is to use ng-annotate instead of ng-strict-di.

I am closing this now, because it is not necessary to change this!
