### ISSUE TITLE
issue with image preview.

### ISSUE THREAD

**Issue by akashjarad** [lpsBetty/angular-croppie#3]
@lpsBetty 
![screenshot from 2016-12-26 16-03-03](https://cloud.githubusercontent.com/assets/5300334/21480625/dff0810c-cb84-11e6-8476-27506832e968.png)

when i run demo it does not show the cropped image at bottom, but when i upload an image from disk it shows cropped image.

![screenshot from 2016-12-26 16-05-49](https://cloud.githubusercontent.com/assets/5300334/21480654/37e37ff4-cb85-11e6-97cc-4d606e577614.png)

**Comment by pyccki** [comment]
@akashjarad
Default Image wasn't meant for preview.
as far as i know, preview were only for new Uploaded Images.

**Comment by akashjarad** [comment]
I want to profile image chang using a md-dialog box using Angular material which show the choose file option for image selection or the current image . Once image selected, it should show the image and provide crop facility and also provide the preview of the crop image.

**Comment by bettysteger** [comment]
@akashjarad Sorry for the late response, so you want an image preview for a given image - is it a image from an URL (what's your "current image") ?

**Comment by akashjarad** [comment]
@lpsBetty  thanks for reply . you have done awesome work .
i have used a  work around solution,
current image is from url only, so on image click i open an modal window and do cropping and return the blob and  converted it to image using b64toBlob and the upload it to server.
