### ISSUE TITLE
rotate example?

### ISSUE THREAD

**Issue by snobrdinrtiste** [lpsBetty/angular-croppie#6]
anyone have a rotate example for this?

**Comment by imashishks** [comment]
Check the  orientation property in the bind function for Croppie.
Valid options are:
1 unchanged
2 flipped horizontally
3 rotated 180 degrees
4 flipped vertically
5 flipped horizontally, then rotated left by 90 degrees
6 rotated clockwise by 90 degrees
7 flipped horizontally, then rotated right by 90 degrees
8 rotated counter-clockwise by 90 degrees

Example - c.bind({
            url: src,
            orientation: 4 // for flipping vertically
          });

You can also use the rotate function!
More info at - https://foliotek.github.io/Croppie/
